language: node_js
node_js:
  - stable

cache: npm

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - npm run build

deploy:
  provider: script
  script: bash ./infrastructure/deploy-website.sh
