language: node_js
node_js:
  - stable

cache: npm

script:
- npm run build

deploy:
  provider: s3
  access_key_id: "AWS_ACCESS_KEY_ID"
  secret_access_key: "AWS_SECRET_KEY"
  bucket: "devicenator.com"
  acl: public_read
  skip_cleanup: true
  local_dir: build
