language: node_js
node_js:
  - stable

cache: npm

before_install:
  - openssl aes-256-cbc -K $encrypted_d3e6cba3603e_key -iv $encrypted_d3e6cba3603e_iv -in devicenator-b243d0d14767.json.enc -out devicenator-b243d0d14767.json -d

script:
- npm run build

deploy:
  provider: gae
  keyfile: devicenator-b243d0d14767.json
  project: devicenator


